@baseUrl = https://202.73.42.183:43901/mobile_central_2_0_0

###

# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "rosalind.yee@nova-hub.com",
  "password": "password",
  "fromAdmin": false
}

###

@token = {{login.response.headers.authorization}}

###

GET {{baseUrl}}/user
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/vesalius/patient-data/1/00-000040
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/vesalius/patient-allergy/1/20-000117
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/vesalius/patient-visit/1/20-000117/2
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/vesalius/patient-visit/1/08-001001/5
Authorization: {{token}}

###

GET {{baseUrl}}/vesalius/get-vital-signs-history/1/08-001001/2020-07-29/BMI
Authorization: {{token}}

###
GET {{baseUrl}}/public/vesalius/getAllDoctorInformation/1

###

GET {{baseUrl}}/public/vesalius/getDoctorInformationByMCR/1/631

###