// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/doctor_data.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 4888963607608290662),
      name: 'DoctorClinicHours',
      lastPropertyId: const IdUid(7, 8283647715738435196),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8570438433828273021),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2338350862618574684),
            name: 'doctorId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7537837262802853328),
            name: 'displaySequence',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 362934598487644110),
            name: 'dayOfTheWeek',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7425462456418266896),
            name: 'dayStartTime',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2040970771847878043),
            name: 'dayEndTime',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 8283647715738435196),
            name: 'byAppointmentOnly',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 981194313715741449),
      name: 'DoctorClinicLocation',
      lastPropertyId: const IdUid(4, 8653907136545547489),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6245117016066111395),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5373241426867984164),
            name: 'doctorId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 2825964323092171795),
            name: 'location',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8653907136545547489),
            name: 'building',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 8881990263305376500),
      name: 'DoctorContact',
      lastPropertyId: const IdUid(5, 7839151249819842936),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8003381138380971233),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5143618017734477176),
            name: 'doctorId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 275821269127908318),
            name: 'displaySequence',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7344059470754999700),
            name: 'contactType',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7839151249819842936),
            name: 'contactValue',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(5, 621559165627320874),
      name: 'DoctorInfoModel',
      lastPropertyId: const IdUid(10, 3119371244662058346),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4480937538677614377),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2276954506085026601),
            name: 'user',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5868429407118457843),
            name: 'mcr',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8908896856355590556),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4028346715647531995),
            name: 'gender',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 3699322812724309681),
            name: 'nationality',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 2359196315094241786),
            name: 'image',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 5825672258705868484),
            name: 'date',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 4157509827758254063),
            name: 'doctorId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 3119371244662058346),
            name: 'allowAppointment',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(1, 1134965209125780950),
            name: 'doctorSpokenLanguage',
            targetId: const IdUid(9, 6837540651065450326)),
        ModelRelation(
            id: const IdUid(2, 5322903034608184290),
            name: 'doctorQualifications',
            targetId: const IdUid(6, 1062854098259929606)),
        ModelRelation(
            id: const IdUid(3, 9026679171552540784),
            name: 'doctorSpecialities',
            targetId: const IdUid(7, 7517099077172568575)),
        ModelRelation(
            id: const IdUid(4, 2120353408747604565),
            name: 'doctorClinicLocation',
            targetId: const IdUid(3, 981194313715741449)),
        ModelRelation(
            id: const IdUid(5, 1300211733452594745),
            name: 'doctorClinicHours',
            targetId: const IdUid(2, 4888963607608290662)),
        ModelRelation(
            id: const IdUid(6, 365214128673774914),
            name: 'doctorContact',
            targetId: const IdUid(4, 8881990263305376500)),
        ModelRelation(
            id: const IdUid(7, 6203008160230486340),
            name: 'doctorSpecialty',
            targetId: const IdUid(8, 4364241087500746010))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(6, 1062854098259929606),
      name: 'DoctorQualification',
      lastPropertyId: const IdUid(4, 8724844005752575999),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1182499722362409923),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 549130259867509140),
            name: 'doctorId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6238909402984082017),
            name: 'displaySequence',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8724844005752575999),
            name: 'qualification',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(7, 7517099077172568575),
      name: 'DoctorSpecialities',
      lastPropertyId: const IdUid(4, 1156704343839483202),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4230895221031139953),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7769827489607488676),
            name: 'doctorId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 425865666537894717),
            name: 'displaySequence',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1156704343839483202),
            name: 'specialities',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(8, 4364241087500746010),
      name: 'DoctorSpecialty',
      lastPropertyId: const IdUid(3, 5300039639931842144),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 466578473659229384),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7935006927311425197),
            name: 'doctorId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5300039639931842144),
            name: 'primarySpecialty',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(9, 6837540651065450326),
      name: 'DoctorSpokenLanguage',
      lastPropertyId: const IdUid(4, 1459747402539245404),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4534227467017390308),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8458759910641610550),
            name: 'doctorId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 207550691976988620),
            name: 'displaySequence',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1459747402539245404),
            name: 'spokenLanguage',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(9, 6837540651065450326),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(8, 2157753452363746149),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [1038166220417243434],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        6337665668278945342,
        3329727610185105253,
        272461230991073430,
        1843658413111148688,
        6475143974182479869,
        1346119577516618682,
        1609867912272813358,
        4503787989580389144,
        8729297190819986159,
        3260742574836081481
      ],
      retiredRelationUids: const [2157753452363746149],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    DoctorClinicHours: EntityDefinition<DoctorClinicHours>(
        model: _entities[0],
        toOneRelations: (DoctorClinicHours object) => [],
        toManyRelations: (DoctorClinicHours object) => {},
        getId: (DoctorClinicHours object) => object.id,
        setId: (DoctorClinicHours object, int id) {
          object.id = id;
        },
        objectToFB: (DoctorClinicHours object, fb.Builder fbb) {
          final dayOfTheWeekOffset = object.dayOfTheWeek == null
              ? null
              : fbb.writeString(object.dayOfTheWeek!);
          final dayStartTimeOffset = object.dayStartTime == null
              ? null
              : fbb.writeString(object.dayStartTime!);
          final dayEndTimeOffset = object.dayEndTime == null
              ? null
              : fbb.writeString(object.dayEndTime!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.doctorId);
          fbb.addInt64(2, object.displaySequence);
          fbb.addOffset(3, dayOfTheWeekOffset);
          fbb.addOffset(4, dayStartTimeOffset);
          fbb.addOffset(5, dayEndTimeOffset);
          fbb.addBool(6, object.byAppointmentOnly);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DoctorClinicHours(
              doctorId: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 6),
              displaySequence: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 8),
              dayOfTheWeek: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              dayStartTime: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              dayEndTime: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              byAppointmentOnly: const fb.BoolReader()
                  .vTableGetNullable(buffer, rootOffset, 16))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    DoctorClinicLocation: EntityDefinition<DoctorClinicLocation>(
        model: _entities[1],
        toOneRelations: (DoctorClinicLocation object) => [],
        toManyRelations: (DoctorClinicLocation object) => {},
        getId: (DoctorClinicLocation object) => object.id,
        setId: (DoctorClinicLocation object, int id) {
          object.id = id;
        },
        objectToFB: (DoctorClinicLocation object, fb.Builder fbb) {
          final locationOffset = object.location == null
              ? null
              : fbb.writeString(object.location!);
          final buildingOffset = object.building == null
              ? null
              : fbb.writeString(object.building!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.doctorId);
          fbb.addOffset(2, locationOffset);
          fbb.addOffset(3, buildingOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DoctorClinicLocation(
              doctorId: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 6),
              location: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              building: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    DoctorContact: EntityDefinition<DoctorContact>(
        model: _entities[2],
        toOneRelations: (DoctorContact object) => [],
        toManyRelations: (DoctorContact object) => {},
        getId: (DoctorContact object) => object.id,
        setId: (DoctorContact object, int id) {
          object.id = id;
        },
        objectToFB: (DoctorContact object, fb.Builder fbb) {
          final contactTypeOffset = object.contactType == null
              ? null
              : fbb.writeString(object.contactType!);
          final contactValueOffset = object.contactValue == null
              ? null
              : fbb.writeString(object.contactValue!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.doctorId);
          fbb.addInt64(2, object.displaySequence);
          fbb.addOffset(3, contactTypeOffset);
          fbb.addOffset(4, contactValueOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DoctorContact(
              doctorId: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 6),
              displaySequence: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 8),
              contactType: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              contactValue: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    DoctorInfoModel: EntityDefinition<DoctorInfoModel>(
        model: _entities[3],
        toOneRelations: (DoctorInfoModel object) => [],
        toManyRelations: (DoctorInfoModel object) => {
              RelInfo<DoctorInfoModel>.toMany(1, object.id):
                  object.doctorSpokenLanguage,
              RelInfo<DoctorInfoModel>.toMany(2, object.id):
                  object.doctorQualifications,
              RelInfo<DoctorInfoModel>.toMany(3, object.id):
                  object.doctorSpecialities,
              RelInfo<DoctorInfoModel>.toMany(4, object.id):
                  object.doctorClinicLocation,
              RelInfo<DoctorInfoModel>.toMany(5, object.id):
                  object.doctorClinicHours,
              RelInfo<DoctorInfoModel>.toMany(6, object.id):
                  object.doctorContact,
              RelInfo<DoctorInfoModel>.toMany(7, object.id):
                  object.doctorSpecialty
            },
        getId: (DoctorInfoModel object) => object.id,
        setId: (DoctorInfoModel object, int id) {
          object.id = id;
        },
        objectToFB: (DoctorInfoModel object, fb.Builder fbb) {
          final userOffset = fbb.writeString(object.user);
          final mcrOffset =
              object.mcr == null ? null : fbb.writeString(object.mcr!);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final genderOffset =
              object.gender == null ? null : fbb.writeString(object.gender!);
          final nationalityOffset = object.nationality == null
              ? null
              : fbb.writeString(object.nationality!);
          final imageOffset =
              object.image == null ? null : fbb.writeString(object.image!);
          final allowAppointmentOffset = object.allowAppointment == null
              ? null
              : fbb.writeString(object.allowAppointment!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, userOffset);
          fbb.addOffset(2, mcrOffset);
          fbb.addOffset(3, nameOffset);
          fbb.addOffset(4, genderOffset);
          fbb.addOffset(5, nationalityOffset);
          fbb.addOffset(6, imageOffset);
          fbb.addInt64(7, object.date?.millisecondsSinceEpoch);
          fbb.addInt64(8, object.doctorId);
          fbb.addOffset(9, allowAppointmentOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final object = DoctorInfoModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..user = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..mcr = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 8)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 10)
            ..gender = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 12)
            ..nationality = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 14)
            ..image = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 16)
            ..date = dateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(dateValue)
            ..doctorId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0)
            ..allowAppointment = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 22);
          InternalToManyAccess.setRelInfo<DoctorInfoModel>(
              object.doctorSpokenLanguage,
              store,
              RelInfo<DoctorInfoModel>.toMany(1, object.id));
          InternalToManyAccess.setRelInfo<DoctorInfoModel>(
              object.doctorQualifications,
              store,
              RelInfo<DoctorInfoModel>.toMany(2, object.id));
          InternalToManyAccess.setRelInfo<DoctorInfoModel>(
              object.doctorSpecialities,
              store,
              RelInfo<DoctorInfoModel>.toMany(3, object.id));
          InternalToManyAccess.setRelInfo<DoctorInfoModel>(
              object.doctorClinicLocation,
              store,
              RelInfo<DoctorInfoModel>.toMany(4, object.id));
          InternalToManyAccess.setRelInfo<DoctorInfoModel>(
              object.doctorClinicHours,
              store,
              RelInfo<DoctorInfoModel>.toMany(5, object.id));
          InternalToManyAccess.setRelInfo<DoctorInfoModel>(object.doctorContact,
              store, RelInfo<DoctorInfoModel>.toMany(6, object.id));
          InternalToManyAccess.setRelInfo<DoctorInfoModel>(
              object.doctorSpecialty,
              store,
              RelInfo<DoctorInfoModel>.toMany(7, object.id));
          return object;
        }),
    DoctorQualification: EntityDefinition<DoctorQualification>(
        model: _entities[4],
        toOneRelations: (DoctorQualification object) => [],
        toManyRelations: (DoctorQualification object) => {},
        getId: (DoctorQualification object) => object.id,
        setId: (DoctorQualification object, int id) {
          object.id = id;
        },
        objectToFB: (DoctorQualification object, fb.Builder fbb) {
          final qualificationOffset = object.qualification == null
              ? null
              : fbb.writeString(object.qualification!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.doctorId);
          fbb.addInt64(2, object.displaySequence);
          fbb.addOffset(3, qualificationOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DoctorQualification(
              doctorId: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 6),
              displaySequence: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 8),
              qualification: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    DoctorSpecialities: EntityDefinition<DoctorSpecialities>(
        model: _entities[5],
        toOneRelations: (DoctorSpecialities object) => [],
        toManyRelations: (DoctorSpecialities object) => {},
        getId: (DoctorSpecialities object) => object.id,
        setId: (DoctorSpecialities object, int id) {
          object.id = id;
        },
        objectToFB: (DoctorSpecialities object, fb.Builder fbb) {
          final specialitiesOffset = object.specialities == null
              ? null
              : fbb.writeString(object.specialities!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.doctorId);
          fbb.addInt64(2, object.displaySequence);
          fbb.addOffset(3, specialitiesOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DoctorSpecialities(
              doctorId: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 6),
              displaySequence: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 8),
              specialities: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    DoctorSpecialty: EntityDefinition<DoctorSpecialty>(
        model: _entities[6],
        toOneRelations: (DoctorSpecialty object) => [],
        toManyRelations: (DoctorSpecialty object) => {},
        getId: (DoctorSpecialty object) => object.id,
        setId: (DoctorSpecialty object, int id) {
          object.id = id;
        },
        objectToFB: (DoctorSpecialty object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.doctorId);
          fbb.addBool(2, object.primarySpecialty);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DoctorSpecialty(
              doctorId: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 6),
              primarySpecialty: const fb.BoolReader()
                  .vTableGetNullable(buffer, rootOffset, 8))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    DoctorSpokenLanguage: EntityDefinition<DoctorSpokenLanguage>(
        model: _entities[7],
        toOneRelations: (DoctorSpokenLanguage object) => [],
        toManyRelations: (DoctorSpokenLanguage object) => {},
        getId: (DoctorSpokenLanguage object) => object.id,
        setId: (DoctorSpokenLanguage object, int id) {
          object.id = id;
        },
        objectToFB: (DoctorSpokenLanguage object, fb.Builder fbb) {
          final spokenLanguageOffset = object.spokenLanguage == null
              ? null
              : fbb.writeString(object.spokenLanguage!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.doctorId);
          fbb.addInt64(2, object.displaySequence);
          fbb.addOffset(3, spokenLanguageOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DoctorSpokenLanguage(
              doctorId: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 6),
              displaySequence: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 8),
              spokenLanguage: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [DoctorClinicHours] entity fields to define ObjectBox queries.
class DoctorClinicHours_ {
  /// see [DoctorClinicHours.id]
  static final id =
      QueryIntegerProperty<DoctorClinicHours>(_entities[0].properties[0]);

  /// see [DoctorClinicHours.doctorId]
  static final doctorId =
      QueryIntegerProperty<DoctorClinicHours>(_entities[0].properties[1]);

  /// see [DoctorClinicHours.displaySequence]
  static final displaySequence =
      QueryIntegerProperty<DoctorClinicHours>(_entities[0].properties[2]);

  /// see [DoctorClinicHours.dayOfTheWeek]
  static final dayOfTheWeek =
      QueryStringProperty<DoctorClinicHours>(_entities[0].properties[3]);

  /// see [DoctorClinicHours.dayStartTime]
  static final dayStartTime =
      QueryStringProperty<DoctorClinicHours>(_entities[0].properties[4]);

  /// see [DoctorClinicHours.dayEndTime]
  static final dayEndTime =
      QueryStringProperty<DoctorClinicHours>(_entities[0].properties[5]);

  /// see [DoctorClinicHours.byAppointmentOnly]
  static final byAppointmentOnly =
      QueryBooleanProperty<DoctorClinicHours>(_entities[0].properties[6]);
}

/// [DoctorClinicLocation] entity fields to define ObjectBox queries.
class DoctorClinicLocation_ {
  /// see [DoctorClinicLocation.id]
  static final id =
      QueryIntegerProperty<DoctorClinicLocation>(_entities[1].properties[0]);

  /// see [DoctorClinicLocation.doctorId]
  static final doctorId =
      QueryIntegerProperty<DoctorClinicLocation>(_entities[1].properties[1]);

  /// see [DoctorClinicLocation.location]
  static final location =
      QueryStringProperty<DoctorClinicLocation>(_entities[1].properties[2]);

  /// see [DoctorClinicLocation.building]
  static final building =
      QueryStringProperty<DoctorClinicLocation>(_entities[1].properties[3]);
}

/// [DoctorContact] entity fields to define ObjectBox queries.
class DoctorContact_ {
  /// see [DoctorContact.id]
  static final id =
      QueryIntegerProperty<DoctorContact>(_entities[2].properties[0]);

  /// see [DoctorContact.doctorId]
  static final doctorId =
      QueryIntegerProperty<DoctorContact>(_entities[2].properties[1]);

  /// see [DoctorContact.displaySequence]
  static final displaySequence =
      QueryIntegerProperty<DoctorContact>(_entities[2].properties[2]);

  /// see [DoctorContact.contactType]
  static final contactType =
      QueryStringProperty<DoctorContact>(_entities[2].properties[3]);

  /// see [DoctorContact.contactValue]
  static final contactValue =
      QueryStringProperty<DoctorContact>(_entities[2].properties[4]);
}

/// [DoctorInfoModel] entity fields to define ObjectBox queries.
class DoctorInfoModel_ {
  /// see [DoctorInfoModel.id]
  static final id =
      QueryIntegerProperty<DoctorInfoModel>(_entities[3].properties[0]);

  /// see [DoctorInfoModel.user]
  static final user =
      QueryStringProperty<DoctorInfoModel>(_entities[3].properties[1]);

  /// see [DoctorInfoModel.mcr]
  static final mcr =
      QueryStringProperty<DoctorInfoModel>(_entities[3].properties[2]);

  /// see [DoctorInfoModel.name]
  static final name =
      QueryStringProperty<DoctorInfoModel>(_entities[3].properties[3]);

  /// see [DoctorInfoModel.gender]
  static final gender =
      QueryStringProperty<DoctorInfoModel>(_entities[3].properties[4]);

  /// see [DoctorInfoModel.nationality]
  static final nationality =
      QueryStringProperty<DoctorInfoModel>(_entities[3].properties[5]);

  /// see [DoctorInfoModel.image]
  static final image =
      QueryStringProperty<DoctorInfoModel>(_entities[3].properties[6]);

  /// see [DoctorInfoModel.date]
  static final date =
      QueryIntegerProperty<DoctorInfoModel>(_entities[3].properties[7]);

  /// see [DoctorInfoModel.doctorId]
  static final doctorId =
      QueryIntegerProperty<DoctorInfoModel>(_entities[3].properties[8]);

  /// see [DoctorInfoModel.allowAppointment]
  static final allowAppointment =
      QueryStringProperty<DoctorInfoModel>(_entities[3].properties[9]);

  /// see [DoctorInfoModel.doctorSpokenLanguage]
  static final doctorSpokenLanguage =
      QueryRelationToMany<DoctorInfoModel, DoctorSpokenLanguage>(
          _entities[3].relations[0]);

  /// see [DoctorInfoModel.doctorQualifications]
  static final doctorQualifications =
      QueryRelationToMany<DoctorInfoModel, DoctorQualification>(
          _entities[3].relations[1]);

  /// see [DoctorInfoModel.doctorSpecialities]
  static final doctorSpecialities =
      QueryRelationToMany<DoctorInfoModel, DoctorSpecialities>(
          _entities[3].relations[2]);

  /// see [DoctorInfoModel.doctorClinicLocation]
  static final doctorClinicLocation =
      QueryRelationToMany<DoctorInfoModel, DoctorClinicLocation>(
          _entities[3].relations[3]);

  /// see [DoctorInfoModel.doctorClinicHours]
  static final doctorClinicHours =
      QueryRelationToMany<DoctorInfoModel, DoctorClinicHours>(
          _entities[3].relations[4]);

  /// see [DoctorInfoModel.doctorContact]
  static final doctorContact =
      QueryRelationToMany<DoctorInfoModel, DoctorContact>(
          _entities[3].relations[5]);

  /// see [DoctorInfoModel.doctorSpecialty]
  static final doctorSpecialty =
      QueryRelationToMany<DoctorInfoModel, DoctorSpecialty>(
          _entities[3].relations[6]);
}

/// [DoctorQualification] entity fields to define ObjectBox queries.
class DoctorQualification_ {
  /// see [DoctorQualification.id]
  static final id =
      QueryIntegerProperty<DoctorQualification>(_entities[4].properties[0]);

  /// see [DoctorQualification.doctorId]
  static final doctorId =
      QueryIntegerProperty<DoctorQualification>(_entities[4].properties[1]);

  /// see [DoctorQualification.displaySequence]
  static final displaySequence =
      QueryIntegerProperty<DoctorQualification>(_entities[4].properties[2]);

  /// see [DoctorQualification.qualification]
  static final qualification =
      QueryStringProperty<DoctorQualification>(_entities[4].properties[3]);
}

/// [DoctorSpecialities] entity fields to define ObjectBox queries.
class DoctorSpecialities_ {
  /// see [DoctorSpecialities.id]
  static final id =
      QueryIntegerProperty<DoctorSpecialities>(_entities[5].properties[0]);

  /// see [DoctorSpecialities.doctorId]
  static final doctorId =
      QueryIntegerProperty<DoctorSpecialities>(_entities[5].properties[1]);

  /// see [DoctorSpecialities.displaySequence]
  static final displaySequence =
      QueryIntegerProperty<DoctorSpecialities>(_entities[5].properties[2]);

  /// see [DoctorSpecialities.specialities]
  static final specialities =
      QueryStringProperty<DoctorSpecialities>(_entities[5].properties[3]);
}

/// [DoctorSpecialty] entity fields to define ObjectBox queries.
class DoctorSpecialty_ {
  /// see [DoctorSpecialty.id]
  static final id =
      QueryIntegerProperty<DoctorSpecialty>(_entities[6].properties[0]);

  /// see [DoctorSpecialty.doctorId]
  static final doctorId =
      QueryIntegerProperty<DoctorSpecialty>(_entities[6].properties[1]);

  /// see [DoctorSpecialty.primarySpecialty]
  static final primarySpecialty =
      QueryBooleanProperty<DoctorSpecialty>(_entities[6].properties[2]);
}

/// [DoctorSpokenLanguage] entity fields to define ObjectBox queries.
class DoctorSpokenLanguage_ {
  /// see [DoctorSpokenLanguage.id]
  static final id =
      QueryIntegerProperty<DoctorSpokenLanguage>(_entities[7].properties[0]);

  /// see [DoctorSpokenLanguage.doctorId]
  static final doctorId =
      QueryIntegerProperty<DoctorSpokenLanguage>(_entities[7].properties[1]);

  /// see [DoctorSpokenLanguage.displaySequence]
  static final displaySequence =
      QueryIntegerProperty<DoctorSpokenLanguage>(_entities[7].properties[2]);

  /// see [DoctorSpokenLanguage.spokenLanguage]
  static final spokenLanguage =
      QueryStringProperty<DoctorSpokenLanguage>(_entities[7].properties[3]);
}
